// CSS build: copies each component file to dist/components/ and concatenates
// everything (tokens first) into dist/index.css for drop-in plain-HTML use.
import { mkdir, readFile, writeFile, readdir, rm, copyFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Order matters: primitives (state-layer) before components that compose them.
const ORDER = [
  "state-layer.css",
  "spinner.css",
  "button.css",
  "button-group.css",
  "toggle-button.css",
  // After toggle-button: the attached bar overrides the radius each option sets.
  "toggle-button-group.css",
  "icon.css",
  // Before text-field: Field owns everything around a control's box, and the
  // components that compose it override only inside that box.
  "field.css",
  "text-field.css",
  // After text-field: all three borrow its look and its focus treatment.
  "textarea.css",
  "select.css",
  "search.css",
  "checkbox.css",
  // After checkbox: radio shares its construction and overrides the shape.
  "radio.css",
  "radio-group.css",
  // After radio: the switch shares their construction and redraws the control.
  "switch.css",
  // Typography before the components that set text inside themselves: both are
  // element-agnostic and neither should win over a component's own type rules.
  "heading.css",
  "text.css",
  "badge.css",
  "avatar.css",
  "disclosure.css",
  "breadcrumbs.css",
  "top-nav.css",
  "side-nav.css",
  // After side-nav: the drawer renders one and overrides its scrolling.
  "mobile-nav.css",
  "tabs.css",
  "segmented-control.css",
  "notice.css",
  // After notice: both are surfaces, and the menu sits above one.
  "menu.css",
  "dialog.css",
  // After dialog: Sheet is the same native-modal construction with different
  // geometry, and its rules are written to replace dialog.css's where they
  // overlap rather than to coexist with them.
  "sheet.css",
  "panel.css",
  // Last on purpose: a class whose job is to hide must not lose the cascade
  // to a component rule that happens to set position or padding.
  "visually-hidden.css",
];

const srcFiles = await readdir(path.join(root, "src"));
const unordered = srcFiles.filter((f) => f.endsWith(".css") && !ORDER.includes(f));
const files = [...ORDER.filter((f) => srcFiles.includes(f)), ...unordered];

await rm(path.join(root, "dist"), { recursive: true, force: true });
await mkdir(path.join(root, "dist/components"), { recursive: true });

const tokensCss = require.resolve("@rata/tokens/css");
const parts = [await readFile(tokensCss, "utf8")];

for (const file of files) {
  const from = path.join(root, "src", file);
  await copyFile(from, path.join(root, "dist/components", file));
  parts.push(await readFile(from, "utf8"));
}

await writeFile(
  path.join(root, "dist/index.css"),
  "/* Generated by @rata/css — tokens + all components. */\n\n" + parts.join("\n")
);

console.log(`@rata/css built: ${files.length} components`);
